import type { RiskFlag } from "@/components/RiskCard";
import type { AnalysisMetrics } from "./analyzeText";

function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function exportReportAsHtml(
  flags: RiskFlag[],
  verdict: string,
  metrics: AnalysisMetrics
): void {
  const highFlags = flags.filter((f) => f.level === "high");
  const medFlags = flags.filter((f) => f.level === "medium");
  const lowFlags = flags.filter((f) => f.level === "low");

  const riskColor = { high: "#dc2626", medium: "#d97706", low: "#16a34a" };
  const riskLabel = { high: "🔴 High Risk", medium: "🟡 Medium Risk", low: "🟢 Low Risk" };

  const renderFlags = (list: RiskFlag[], level: string) => {
    if (!list.length) return "";
    return `
      <h2 style="color:${riskColor[level as keyof typeof riskColor]};border-bottom:2px solid ${riskColor[level as keyof typeof riskColor]};padding-bottom:6px;margin-top:28px;">
        ${riskLabel[level as keyof typeof riskLabel]} (${list.length})
      </h2>
      ${list.map((f) => `
        <div style="border-left:3px solid ${riskColor[f.level]};padding:12px 16px;margin:12px 0;background:#fafafa;border-radius:4px;">
          <blockquote style="font-style:italic;color:#333;margin:0 0 8px 0;font-family:Georgia,serif;">"${escapeHtml(f.text)}"</blockquote>
          <p style="font-size:13px;color:#555;margin:4px 0;">${escapeHtml(f.explanation)}</p>
          ${f.suggestion ? `<p style="font-size:12px;color:#16a34a;margin:8px 0 0 0;"><strong>Suggestion:</strong> ${escapeHtml(f.suggestion)}</p>` : ""}
        </div>
      `).join("")}
    `;
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Aura Forensic Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif; max-width: 800px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #888; }
    .metrics-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 20px 0; }
    .metric-card { background: #f5f5f5; border-radius: 8px; padding: 14px; }
    .metric-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1.5px; color: #888; }
    .metric-value { font-size: 20px; font-weight: 700; font-family: 'JetBrains Mono', monospace; margin-top: 4px; }
    .verdict { background: #f8f8f8; border-radius: 8px; padding: 16px; margin: 20px 0; border-left: 4px solid #333; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Aura Forensic Manuscript Report</h1>
  <p class="subtitle">Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}</p>

  <div class="metrics-grid">
    <div class="metric-card">
      <div class="metric-label">Words</div>
      <div class="metric-value">${metrics.totalWords.toLocaleString()}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Sentences</div>
      <div class="metric-value">${metrics.totalSentences}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Paragraphs</div>
      <div class="metric-value">${metrics.totalParagraphs}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Consistency</div>
      <div class="metric-value">${metrics.consistencyScore}/100</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Readability</div>
      <div class="metric-value">Grade ${metrics.overallReadability.fleschKincaid}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Vocab Richness</div>
      <div class="metric-value">${metrics.vocabMetrics.typeTokenRatio}</div>
    </div>
  </div>

  <div class="verdict">
    <strong>Verdict:</strong> ${escapeHtml(verdict)}
  </div>

  <h2 style="margin-top:32px;">📊 Evidence Points (${flags.length})</h2>

  ${renderFlags(highFlags, "high")}
  ${renderFlags(medFlags, "medium")}
  ${renderFlags(lowFlags, "low")}

  <hr style="margin:32px 0;border:none;border-top:1px solid #e5e5e5;">
  <p style="font-size:11px;color:#aaa;text-align:center;">
    Generated by Aura Academic Integrity Suite · Integrated with Scrapy Web Crawl & Nvidia AI Analysis
  </p>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `aura-report-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
